"""create hanzi table

Revision ID: 8ef266166f25
Revises: 
Create Date: 2026-05-24 15:56:23.408297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef266166f25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hanzi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character', sa.String(length=10), nullable=False),
    sa.Column('pinyin', sa.String(length=50), nullable=False),
    sa.Column('meaning_pl', sa.String(length=255), nullable=False),
    sa.Column('meaning_en', sa.String(length=255), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('theme_category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hanzi_character'), 'hanzi', ['character'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hanzi_character'), table_name='hanzi')
    op.drop_table('hanzi')
    # ### end Alembic commands ###
